[style.description]
underline = false
bold = false
italic = false

[style.command_name]
foreground = { ansi = 160 }
underline = false
bold = true
italic = false

[style.example_text]
foreground = "blue"
underline = false
bold = false
italic = false

[style.example_code]
# foreground = "green"
foreground = { ansi = 172 }
underline = false
bold = false
italic = false

[style.example_variable]
# foreground = "green"
foreground = { ansi = 184 }
underline = false
bold = false
italic = false

[display]
compact = false
use_pager = false

[updates]
auto_update = true
auto_update_interval_hours = 168

[directories]
custom_pages_dir = "/home/krzysztof_krysiak/.local/share/tealdeer/pages/"
