#! /bin/sh
xset r rate 180 60
pgrep -x sxhkd > /dev/null || sxhkd &
~/.screenlayout/acer+dell.sh &
/usr/bin/feh --bg-scale ~/dotfiles/wallpapers/earth_sunrise_from_space-wallpaper-2560x1440.jpg &
copyq &
~/dotfiles/scripts/polybar_launch.sh &


bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap          10
bspc config top_padding         30
bspc config normal_border_color "#2f343f"
bspc config active_border_color "#003366"
bspc config focused_border_color "#0066ff"


# set $bg-color            #2f343f
# set $inactive-bg-color   #2f343f
# set $text-color          #f3f4f5
# # set $inactive-text-color #676e7d
# set $inactive-text-color #cccccc
# set $active-text-color   #990000
# set $border-color        #ff0000
# set $urgent-bg-color     #e53935
# set $urgent-bg-colorx    #e57975
# set $indicator-color     #ffff00
# set $separator-color     #757575

set $black               #000000
set $bg-color            #2f343f
set $inactive-bg-color   #2f343f
set $text-color          #f3f4f5
# set $inactive-text-color #676e7d
set $inactive-text-color #888888
set $active-text-color   #ffffff
set $active-tab-color   #0066cc
set $border-color        #0066cc
# set $border-color        #0066cc
set $urgent-bg-color     #e53935
set $urgent-bg-colorx    #e57975
set $indicator-color     #ffff00
set $separator-color     #757575

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
