#! /bin/sh

### Monitors ###

~/.screenlayout/acer+dell.sh &

bspc monitor DP-3 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor DP-1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10

### Autostart ###

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x crow > /dev/null || crow &
pgrep -x copyq > /dev/null || copyq &
/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh &
xset r rate 200 50
~/.fehbg &
~/dotfiles/scripts/polybar_launch.sh &
sudo ~/dotfiles/scripts/keychron-fn.sh &

### BSPWM configuration ###

bspc config border_width                2
bspc config window_gap                  10
bspc config top_padding                 20
bspc config left_padding                0
bspc config right_padding               0

bspc config single monocle              false
bspc config click_to_focus              true
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_by_distance           true
bspc config focus_follows_pointer       true
bspc config history_aware_focus         true
bspc config pointer_modifier            mod4
bspc config pointer_action1             move
bspc config pointer_action2             resize_side
bspc config pointer_action3             resize_corner
bspc config remove_disabled_monitors    true
bspc config merge_overlapping_monitors  true

### BSPWM rules ###

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

### BSPWM coloring ###

# set $black               #000000
# set $bg-color            #2f343f
# set $inactive-bg-color   #2f343f
# set $text-color          #f3f4f5
# # set $inactive-text-color #676e7d
# set $inactive-text-color #888888
# set $active-text-color   #ffffff
# set $active-tab-color   #0066cc
# set $border-color        #0066cc
# # set $border-color        #0066cc
# set $urgent-bg-color     #e53935
# set $urgent-bg-colorx    #e57975
# set $indicator-color     #ffff00
# set $separator-color     #757575

bspc config normal_border_color "#2f343f"
bspc config active_border_color "#003366"
bspc config focused_border_color "#0066ff"
